# Generated by Django 5.2.4 on 2025-08-26 13:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_type', models.CharField(choices=[('AIDED', 'Aided'), ('SFM', 'sfm'), ('SFW', 'sfw')], max_length=20)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(blank=True, help_text='Original department name from Excel import', max_length=100, null=True, verbose_name='Department Name (from Excel)')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('staff_category', models.CharField(max_length=100)),
                ('dept_category', models.CharField(max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('date_of_joining', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session', models.IntegerField(default=0, help_text='Dynamically allocated session value (can be negative)')),
                ('random', models.IntegerField(default=0)),
                ('fixed_session', models.IntegerField(default=0, help_text='Fixed session allocation (can be negative)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.IntegerField(blank=True, help_text='Role of the user: 1=Admin, 2=Squad, 3=HOD, 4=Staff', null=True)),
                ('password', models.CharField(help_text='Password for login (stored in plain text for now)', max_length=128)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.designation')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'db_table': 'staff_staff',
                'ordering': ['name'],
            },
        ),
    ]
