# Generated by Django 5.1.6 on 2025-08-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='random',
            field=models.IntegerField(default=0),
        ),
    ]
