# Generated by Django 5.2.4 on 2025-08-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='invigilation_slots',
            field=models.IntegerField(default=0),
        ),
    ]
