# Generated by Django 5.2.4 on 2025-08-15 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_invigilation_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='invigilation_slots',
        ),
    ]
