# Generated by Django 5.2.4 on 2025-08-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='fixed_session',
            field=models.PositiveIntegerField(blank=True, default=None, help_text="Fixed session allocation that shouldn't be modified by automatic distribution", null=True),
        ),
    ]
