# Generated by Django 5.2.4 on 2025-08-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staff_fixed_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='fixed_session',
            field=models.IntegerField(default=0, help_text='Fixed session allocation (can be negative)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='session',
            field=models.IntegerField(default=0, help_text='Dynamically allocated session value (can be negative)'),
        ),
    ]
