# Generated by Django 5.2.4 on 2025-08-02 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staff_fixed_session_alter_staff_session'),
    ]

    operations = [
    ]
