# Generated by Django 5.2.4 on 2025-08-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20250802_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='date_of_joining',
            field=models.TextField(blank=True, null=True),
        ),
    ]
