# Generated by Django 5.2.4 on 2025-08-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDate',
            fields=[
                ('day_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'verbose_name': 'Exam Date',
                'verbose_name_plural': 'Exam Dates',
                'db_table': 'exam_date',
            },
        ),
    ]
