# Generated by Django 4.2.23 on 2025-07-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('shift', models.CharField(choices=[('FN', 'Forenoon'), ('AN', 'Afternoon')], max_length=2)),
                ('session_number', models.IntegerField(choices=[(1, 'Session 1'), (2, 'Session 2')])),
                ('student_type', models.CharField(choices=[('SFM', 'SFM Students'), ('SFW', 'SFW Students')], max_length=3)),
            ],
        ),
    ]
