# Generated by Django 5.2.4 on 2025-08-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvigilationConstraint',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('is_hard', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'new_constraints',
            },
        ),
    ]
