# Generated by Django 5.2.4 on 2025-08-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvigilationSchedule',
            fields=[
                ('serial_number', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('hall_no', models.CharField(max_length=50)),
                ('hall_department', models.CharField(max_length=100)),
                ('staff_id', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('staff_category', models.CharField(blank=True, max_length=100, null=True)),
                ('dept_category', models.CharField(max_length=50)),
                ('double_session', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'invigilation_schedule',
            },
        ),
    ]
