# Generated by Django 5.1.6 on 2025-08-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invigilation_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invigilationschedule',
            name='hall_dept_category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
