# Generated by Django 5.1.6 on 2025-08-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invigilation_schedule', '0002_invigilationschedule_hall_dept_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invigilationschedule',
            name='dept_category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invigilationschedule',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invigilationschedule',
            name='hall_dept_category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invigilationschedule',
            name='staff_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
