# Generated by Django 5.2.4 on 2025-08-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invigilation_schedule', '0003_alter_invigilationschedule_dept_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invigilationschedule',
            name='dept_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
