# Generated by Django 5.2.4 on 2025-07-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeptType', models.CharField(max_length=100)),
                ('Block', models.CharField(max_length=100)),
                ('DeptName', models.CharField(max_length=100)),
                ('HallNo', models.CharField(max_length=50, unique=True)),
                ('Strength', models.PositiveIntegerField()),
                ('Benches', models.PositiveIntegerField()),
            ],
        ),
    ]
