# Generated by Django 5.2.4 on 2025-08-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_category', models.CharField(max_length=100)),
                ('block', models.CharField(default='-', max_length=100)),
                ('dept_name', models.CharField(max_length=100)),
                ('hall_no', models.CharField(max_length=50, unique=True)),
                ('strength', models.PositiveIntegerField(default=0)),
                ('benches', models.PositiveIntegerField(default=0)),
                ('days', models.IntegerField(default=0)),
                ('staff_allotted', models.CharField(default='Not Allotted', max_length=20)),
                ('staff_required', models.IntegerField(default=1)),
                ('required_session', models.IntegerField(default=2)),
            ],
        ),
    ]
