# Generated by Django 5.2.4 on 2025-07-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Benches',
            new_name='benches',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='Block',
            new_name='block',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='DeptName',
            new_name='dept_name',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='HallNo',
            new_name='hall_no',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='Strength',
            new_name='strength',
        ),
        migrations.RemoveField(
            model_name='room',
            name='DeptType',
        ),
        migrations.AddField(
            model_name='room',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='dept_category',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='staff_allotted',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
