# Generated by Django 5.2.4 on 2025-07-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_rename_benches_room_benches_rename_block_room_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='staff_required',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='benches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='block',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='staff_allotted',
            field=models.CharField(default='Not Allotted', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='strength',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
