# Generated by Django 5.2.4 on 2025-07-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0003_room_staff_required_alter_room_benches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='total_staff_required',
            field=models.IntegerField(default=2),
        ),
    ]
