# Generated by Django 5.2.4 on 2025-08-02 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0004_room_total_staff_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='total_staff_required',
            new_name='required_session',
        ),
    ]
